close all;
% clc;
current_path = pwd;
addpath(genpath([pwd,'/Model']))
addpath(genpath([pwd,'/AutoGeneratedFiles']))
addpath(genpath([pwd,'/config']))
addpath(genpath([pwd,'/ipopt']))
addpath(genpath([pwd,'/ipopt_functions']))
addpath(genpath([pwd,'/utils']))
addpath(genpath([pwd,'/utils/matlab_utilities']))

addpath_matlab_utilities('general', 'strings', 'yaml', 'ros', 'sim', 'plot', 'validation');

cd([pwd, '/Model/GlobalVariables'])
FilePaths
GlobalVariables
cd(current_path)