%% Saves all of the file path names

global GLOBAL_PATH MODEL_PATH MAIN_PATH AUTOGEN_PATH SIM_PATH OPT_PATH

GLOBAL_PATH = pwd;
MODEL_PATH = fileparts(GLOBAL_PATH);
MAIN_PATH = fileparts(MODEL_PATH);
AUTOGEN_PATH = [MAIN_PATH, '\AutoGeneratedFiles'];
SIM_PATH = [MAIN_PATH, '\Simulation'];
OPT_PATH = [MAIN_PATH, '\Optimization'];
